routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProjectController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('dashboard', PostController::class)->middleware(['auth']);

Route::get('/', function () {
    return view('welcome');
});

Route::resource('project', ProjectController::class)->middleware(['auth']);

Route::get('/tasks', [PostController::class, 'tasks'])->middleware(['auth']);
Route::get('/show', [PostController::class, 'show'])->middleware(['auth']);
Route::get('/projects', [ProjectController::class, 'index'])->middleware(['auth']);
Route::get('/create', [ProjectController::class, 'create'])->middleware(['auth']);
//Route::get('project/edit', [ProjectController::class, 'edit'])->middleware(['auth']);
//Route::get('project/update', [ProjectController::class, 'update'])->middleware(['auth']);
Route::post('/store', [ProjectController::class, 'store'])->middleware(['auth']);



//Route::get('/dashboard', [PostController::class, 'index' ])->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

    protected $fillable = [
    	'name', 'email'
    ];
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;
use App\Models\Post;
use App\Models\Project;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
  //      $posts = Post::all();
        $projects = Project::all();
    //    var_dump($posts);
        return view('project.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = auth()->user();
        $user = $user['email'];
        return view('project.create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
        ]);

        Project::create($request->all());

        return redirect('projects')->with('success', 'Project created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
    //    var_dump($project);
    //    exit;
        $posts = Post::all();
     //   var_dump($posts['idproj']);
   //     exit;
        return view('project.show', compact('project', 'posts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        return view('project.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        $request->validate([
            'email' => 'required',
            'name' => 'required',
        ]);

        $project->update($request->all());

        return redirect()->route('project.index')->with('success', 'Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
         $project ->delete();

        return redirect()->route('project.index')
                        ->with('success', 'post deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/project/create.blade.php
@extends('layout')
@section('main_content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Project</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="/projects"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="/store" method="POST">
    @csrf

     <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Name:</strong>
                <textarea class="form-control" style="height:150px" name="name" placeholder="Name"></textarea>
            </div>
        </div>
        <input type="hidden" name="email" value="{{ $user }}">
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

resources/views/project/edit.blade.php
@extends('layout')
@section('main_content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Post</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="/projects"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('project.update',$project->id) }}" method="POST">
        @csrf

        @method('PUT')
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Email:</strong>
                    <input type="text" name="email" value="{{ $project->email }}" class="form-control" placeholder="Email">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <textarea class="form-control" style="height:150px" name="name" placeholder="Name">{{ $project->name }}</textarea>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

resources/views/project/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Список проектов </h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="/create"> Создать новый</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>Email</th>
            <th>Project name</th>
        </tr>
        @foreach ($projects as $project)
        <tr>
            <td>{{ $project->email }}</td>
            <td>{{ $project->name }}</td>
            <td><form action="{{ route('project.destroy',$project->id) }}" method="POST">
                 <a class="btn btn-info" href="{{ route('project.show',$project->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('project.edit',$project->id) }}">Edit</a>
                
   
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>


                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/project/show.blade.php
@extends('layout')
@section('main_content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Project</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="/projects"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $project->email }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $project->name }}
            </div>
        </div>

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Список задач </h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('dashboard.create', ['id'=>$project->id]) }}"> Создать новую</a>
            </div>
        </div>
    </div>

    <table class="table table-bordered">
        <tr>
            <th>Email</th>
            <th>Status</th>
            <th>Message</th>
        </tr>
        @foreach ($posts as $post)
        @if ($post->idproj == $project->id)

        <tr>
            <td>{{ $post->email }}</td>
            <td>{{ $post->status }}</td>
            <td>{{ $post->message }}</td>
            <td><form action="{{ route('dashboard.destroy',$post->id) }}" method="POST">
                 <a class="btn btn-info" href="{{ route('dashboard.show',$post->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('dashboard.edit',$post->id) }}">Edit</a>
                
   
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endif
        @endforeach
    </table>


                </div>
            </div>
        </div>
    </div>











    </div>
@endsection