routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProjectController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('dashboard', PostController::class)->middleware(['auth']);

Route::get('/', function () {
    return view('welcome');
});

Route::resource('project', ProjectController::class)->middleware(['auth']);

Route::get('/tasks', [PostController::class, 'tasks'])->middleware(['auth']);
Route::get('/show', [PostController::class, 'show'])->middleware(['auth']);
Route::get('/projects', [ProjectController::class, 'index'])->middleware(['auth']);
Route::get('/create', [ProjectController::class, 'create'])->middleware(['auth']);
//Route::get('project/edit', [ProjectController::class, 'edit'])->middleware(['auth']);
//Route::get('project/update', [ProjectController::class, 'update'])->middleware(['auth']);
Route::post('/store', [ProjectController::class, 'store'])->middleware(['auth']);



//Route::get('/dashboard', [PostController::class, 'index' ])->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
    	'email', 'status', 'message', 'idproj'
    ];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
       // var_dump($posts);
        return view('dashboard', compact('posts'));

    }

    public function tasks()
    {
        $posts = Post::all();
        return view('posts.tasks', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $id = $request->all();
        $id = $id['id'];
        $user = auth()->user();
        $user = $user['email'];
        return view('posts.create', compact('user', 'id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'email' => 'required',
            'status' => 'required',
            'message' => 'required',
            'idproj' => 'required',
        ]);

        Post::create($request->all());

        return redirect()->route('dashboard.index')->with('success', 'Post created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $dashboard)
    {
        return view('posts.show', compact('dashboard'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $dashboard)
    {   
        return view('posts.edit', compact('dashboard'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $dashboard)
    {
        $request->validate([
            'email' => 'required',
            'status' => 'required',
            'message' => 'required',
        ]);

        $dashboard->update($request->all());

        return redirect()->route('dashboard.index')->with('success', 'Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $dashboard)
    {
        $dashboard ->delete();

        return redirect()->route('dashboard.index')
                        ->with('success', 'post deleted successfully');
    }
}

resources/views/posts/create.blade.php
@extends('layout')
@section('main_content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Post</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="/tasks"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('dashboard.store') }}" method="POST">
    @csrf

     <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Message:</strong>
                <textarea class="form-control" style="height:150px" name="message" placeholder="Message"></textarea>
            </div>
        </div>
        <input type="hidden" name="email" value="{{ $user }}">
        <input type="hidden" name="status" value="new">

        <input type="hidden" name="idproj" value="{{ $id }}">
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

resources/views/posts/edit.blade.php
@extends('layout')
@section('main_content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Post</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="/tasks"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('dashboard.update',$dashboard->id) }}" method="POST">
        @csrf

        @method('PUT')
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Email:</strong>
                    <input type="text" name="email" value="{{ $dashboard->email }}" class="form-control" placeholder="Email">
                </div>
            </div>

           

            <div class="col-xs-12 col-sm-12 col-md-12">
            
                <div class="form-check">
                    @if ($dashboard->status == "new")
                    <input class="form-check-input" type="radio" name="status" id="status1" value="new" checked>
                    @else
                    <input class="form-check-input" type="radio" name="status" id="status1" value="new">
                    @endif
                    <label class="form-check-label" for="status1">
                        New
                    </label>
                </div>
                <div class="form-check">
                    @if ($dashboard->status == "in progress")
                    <input class="form-check-input" type="radio" name="status" id="status2" value="in progress" checked>
                    @else
                    <input class="form-check-input" type="radio" name="status" id="status2" value="in progress">
                    @endif
                    <label class="form-check-label" for="status2">
                        in progress
                    </label>
                </div>
                <div class="form-check">
                    @if ($dashboard->status == "done")
                    <input class="form-check-input" type="radio" name="status" id="status3" value="done" checked>
                    @else
                    <input class="form-check-input" type="radio" name="status" id="status3" value="done">
                    @endif
                    <label class="form-check-label" for="status3">
                        done
                    </label>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Message:</strong>
                    <textarea class="form-control" style="height:150px" name="message" placeholder="Message">{{ $dashboard->message }}</textarea>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

resources/views/posts/show.blade.php
@extends('layout')
@section('main_content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Post</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="/tasks"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $dashboard->email }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status:</strong>
                {{ $dashboard->status }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Message:</strong>
                {{ $dashboard->message }}
            </div>
        </div>

    </div>
@endsection

resources/views/posts/tasks.blade.php
@extends('layout')
@section('main_content')

<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Список задач </h2>
            </div>
            
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>Email</th>
            <th>Status</th>
            <th>Message</th>
        </tr>
        @foreach ($posts as $post)
        <tr>
            <td>{{ $post->email }}</td>
            <td>{{ $post->status }}</td>
            <td>{{ $post->message }}</td>
            <td><form action="{{ route('dashboard.destroy',$post->id) }}" method="POST">
                 <a class="btn btn-info" href="{{ route('dashboard.show',$post->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('dashboard.edit',$post->id) }}">Edit</a>
                
   
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    
@endsection